[supabase]
url = "https://tpiaixxjclalpewqutue.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwaWFpeHhqY2xhbHBld3F1dHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MTY5NzUsImV4cCI6MjA4MjQ5Mjk3NX0.eAi9bekDjTm3gDjiGP5GcEvwu32FceNGlfJjIQ5PY4c"